### PR TITLE
Add option to allow silent overwriting of files

### PR DESCRIPTION
**Pull request by ahosgood**
I was actually using the "feature" of overwriting files from `v0.1.0` which was removed in `v0.2.0`.

It would be really helpful if it could be added back in as an option. 🙏

### CODE REVIEW

**Comment by ahosgood** [comment]
@emmercm would it help if I were to also update the docs/changelog etc. or would you want to do that?

**Comment by emmercm** [comment]
Ah, thank you for the PR @ahosgood ! Let me think on the best way to organize the feature, I may release a major version bump for it.

**Comment by emmercm** [comment]
Let me know how this looks to you @ahosgood : https://github.com/emmercm/metalsmith-include-files/pull/136.

**Comment by ahosgood** [comment]
https://github.com/emmercm/metalsmith-include-files/pull/136 looks like it addresses this now - thank you @emmercm 🙌🏼

**Pull request closed without merging**
